export const siteConfig = {
  companyName: 'PI Metairie',
  domain: 'privateinvestigatormetairie.com',
  siteUrl: 'https://privateinvestigatormetairie.com',
  phone: '+15048333716',
  phoneDisplay: '(504) 833-3716',
  address: 'One Galleria Blvd., Suite 1900, Metairie, LA 70001',
  email: 'info@privateinvestigatormetairie.com',
  formEndpoint: 'https://formspree.io/f/xkopjyve',
  kwPrimary: 'Private Investigator Metairie',
  locationFull: 'Metairie, Louisiana',
  locationCity: 'Metairie',
  locationState: 'Louisiana',
  locationStateShort: 'LA',
  locationCounty: 'Jefferson Parish',
  nearbyCities: ['Kenner', 'Harahan', 'River Ridge', 'Gretna', 'Harvey', 'Marrero', 'New Orleans'],
  serviceAreas: ['Metairie', 'Kenner', 'Harahan', 'Gretna', 'Harvey', 'Marrero'],
  colors: {
    primary: '#0f1a2e',
    accent: '#c49a3c',
    bg: '#f7f8fa',
  },
  disclaimer: 'This is a referral website. Not a licensed private investigation agency.',
};
